species.1 <- iberolacerta.clade$species$monticola
species.2 <- iberolacerta.clade$species$cyreni
env <- euro.worldclim
type <- "glm"
f = NULL
nreps = 99
test.type = "asymmetric"
nback = 1000
bg.source = "default"
low.memory = FALSE
rep.dir = NA
verbose = FALSE
clamp = TRUE
