rm(list=ls())
setwd("~/Dropbox/R Projects/ENMTools")
source("ENMToolsTest.R")
test0 <- raster.sum(x = "pc1.asc")
test1 <- raster.overlap(x = "pc1.asc", y = "pc2.asc")
test2 <- raster.breadth(x = "pc1.asc")
test3 <- raster.standardize(infile = "pc2.asc", outfile = "standardize.asc")
test4 <- reps.identity(infiles = c("ahli.csv", "allogus_east.csv"), outfile = "identity.csv", reps = 2)
test5 <- reps.background.asc(infile = "pc1.asc", outfile = "backtest1.csv", 10, 10 )
test6 <- reps.background.csv(infile = "ahli.csv", outfile = "backtest2.csv", 14, 20)
test7 <- reps.rangebreak.line(infiles = c("ahli.csv", "allogus_east.csv"), outfile = "rangebreak_line.csv", reps = 10, background.raster="pc2.asc")
test8 <- reps.rangebreak.blob(infiles = c("allogus_east.csv", "ahli.csv"), outfile = "rangebreak_blob.csv", reps = 10)
test9 <- reps.rangebreak.ribbon(infiles = c("allogus_east.csv", "ahli.csv"), outfile = "rangebreak_ribbon.csv", reps = 10, width=.2, background.raster="pc2.asc")
test10 <- raster.sample(infile = "pc2.asc", outfile = "rastersample.csv", sample.type="linear", points = 10, reps = 10)

#note to self: add function for raster correlations and produce a corrplot using library(corrplot)